services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgress_db

  pgAdmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
    container_name: pgadmin4

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    container_name: search_engine
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"


volumes:
  postgres_data:
  pgadmin-data:
  certs:
    driver: local
