# Generated by Django 4.2 on 2023-06-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="recipient",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(max_length=255),
        ),
    ]
