# Generated by Django 4.2 on 2023-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="innovation",
            name="in_progress",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="innovation",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="innovation",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
