# Generated by Django 4.2 on 2023-05-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="innovation",
            name="innovation_description",
        ),
        migrations.AddField(
            model_name="innovation",
            name="abstract",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="innovation",
            name="innovation_file",
            field=models.FileField(default=1, upload_to="innovation/files"),
            preserve_default=False,
        ),
    ]
