# Generated by Django 4.2 on 2023-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovation", "0002_innovation_in_progress_innovation_rejected_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="innovation",
            name="in_progress",
        ),
        migrations.RemoveField(
            model_name="innovation",
            name="rejected",
        ),
        migrations.RemoveField(
            model_name="innovation",
            name="verified",
        ),
        migrations.AddField(
            model_name="innovation",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
