# Generated by Django 4.2 on 2023-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="published_at",
            field=models.DateField(),
        ),
    ]
