# Generated by Django 4.2 on 2023-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0002_alter_publication_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="published_at",
            field=models.DateField(blank=True),
        ),
    ]
