# Generated by Django 4.2 on 2023-06-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="class_course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OD20-COE", "OD20-COE"),
                    ("OD21-COE", "OD21-COE"),
                    ("OD22-COE", "OD-22-COE"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Computer Department", "Computer Department"),
                    ("Mining Department", "Mining Department"),
                    (
                        "Mechanical Engineering Department",
                        "Mechanical Engineering Department",
                    ),
                    ("BioTech Department", "BioTech Department"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="education_background",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="employee_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_reg_no",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Head Of Department", "Head Of Department"),
                    ("Lecture", "Lecture"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
